### ISSUE TITLE
assertActionUsesMiddleware and assertRouteUsesMiddleware doesn't respect excludedMiddleware

### ISSUE THREAD

**Issue by chrillep** [jasonmccreary/laravel-test-assertions#37] opened 2022-02-18 11:51 UTC
if using withoutMiddleware
https://laravel.com/docs/9.x/middleware#excluding-middleware

the middleware will still show up as being used on
assertActionUsesMiddleware and assertRouteUsesMiddleware

**Comment by chrillep** [comment] 2022-02-19 17:26
I'll give an example if needed.
just wanted to get my finding out of the way, before I forgot 😊

**Comment by jasonmccreary** [comment] 2022-02-19 17:28
@chrillep, no, the issue is pretty straightforward. Probably won't get to the fix for a while though. Feel free to try a PR.

**Comment by chrillep** [comment] 2022-03-12 11:35
> @chrillep, no, the issue is pretty straightforward. Probably won't get to the fix for a while though. Feel free to try a PR.

happily someone else fixed this 🚀

however the Fix isn't releases yet.
so until then using dev-master 😊

https://packagist.org/packages/jasonmccreary/laravel-test-assertions#dev-master


thanks fo making my testlife easier 🎉

**Comment by jasonmccreary** [comment] 2022-03-12 13:10
@chrillep, is it working for you as expected on `dev-master`? If so, I'll close this and tag a release.

**Comment by chrillep** [comment] 2022-03-20 12:11
> @chrillep, is it working for you as expected on `dev-master`? If so, I'll close this and tag a release.

yes it works. ty :) 👍🏼

**Closed as completed** 2022-03-20 13:47 UTC
Labels: bug
